### ISSUE TITLE
Making a link to another location in the documentation

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes_manual#13]
How can I make a link?
Now I have this in integer for example which works:

```
Related
-------
Float_

.. _Float: float.html
```

But I needed to add .html which shouldn't be the case I assume.

**Comment by JacquesLucke** [comment]
hmmm unfortunally I don't know :D
I will try to find it out if you didn't already.. I think I only know how to create external links and didn't found out to make links within the manual.. Will have to check that. 
I'm not very used to sphinx and rst myself so far, unfortunally.

**Comment by hapit** [comment]
http://www.sphinx-doc.org/en/stable/markup/inline.html

One way is as reference, then you need a label as the reference target.
```
### Label: 
.. _my-reference-label:
### Link:
:ref:`Text displayed for Link <my-reference-label>`
```
Other way is to directly link to the document.
```
:doc:`/path/to/file`   # Linktext is caption of target page
:doc:`Linktext </path/to/file>`
```

The problem with labes is, that they must be unique throughout the manual.
I would suggest using :doc: to make links to other documents and :ref: inside a page with a unique page prefix for the label. The problem with :doc: is if the page is moved sometime in the future.

What is your oppinion about it?

**Comment by OmarEmaraDev** [comment]
We no longer use sphinx.
