### ISSUE TITLE
toctree depth

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes_manual#16]
How deep should the toctree in the index.rst pages be?
This looks very unorganised: http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/index.html

Maybe there should only be the category names, what do you think?

**Comment by hapit** [comment]
You are right. The depth is to high.
The problem is, the toctree shows categories and sections. 
With the depth of 2 it only shows Categories and Nodes.

**Comment by hapit** [comment]
After one year with no comments, I think everybody is happy with the depth of 2.
I close the issue.
