### ISSUE TITLE
Manual translation (fr)

### ISSUE THREAD

**Issue by taserflanger** [JacquesLucke/animation_nodes_manual#27]
I would like know if it is planed to have a manual translation, and how it would be organized. like:
 en -> docs
fr -> docs
I could start translating the docs in french

**Comment by JacquesLucke** [comment]
Hey thanks for your engagement. Unfortunately I think we should focus on the english manual still. It would add way too much work for all of us. Translating the whole manual is a huge task and even the english manual is not perfect everywhere yet. (it is becoming better all the time though)

**Comment by taserflanger** [comment]
No problem, I will try to improve the english version as I can , though my English is pretty bad, and I don't know every thing about the addon

**Comment by JacquesLucke** [comment]
I don't think that anyone knows everything about the addon :D Not even me.

Maybe you can read the manual to learn about individual nodes and if you notice that the manual could be improved for this node, improve it.
