### ISSUE TITLE
Animation not 

### ISSUE THREAD

**Issue by drnn1076** [JacquesLucke/animation_nodes_manual#43]
Hello,

I've created an animation using the nodes of two empty plain-axis where the rotation of the second axis depends on the angle of the first one. It is plays fine and in-sync on the 3D viewer, but when I send to render the animation to have a video file the second axis is not synchronised with the first one. 

I'm using Animation Nodes 2.1.2 on blender 2.79b

Thanks for any help. If needed I can send the *.blend file.

**Comment by hapit** [comment]
This repository is for the animation nodes manual.
Please ask your question for using animation nodes not on GitHub.
You can aks you question an Blender Stackexchange:
https://blender.stackexchange.com/
or at blenderartist.com
