### ISSUE TITLE
"Reversed" misspelled as "Revesred"

### ISSUE THREAD

**Issue by Heten-Daiya** [JacquesLucke/animation_nodes_manual#44]
Hi Jacques,

I'm really excited to be getting my hands whet in animation nodes addon, I was going through the manual and realized there was a small typing error. tried to fix it my self but couldn't so thought to bring to your attention

https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/vector/vector_distance.html

**Comment by hapit** [comment]
Fixed with 7658a8466d27cdcaa2325bca7bf7d0075d2d1435
