### ISSUE TITLE
Subprograms > Loops what happened? 

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes_manual#48]
Hi the subprograms loops examples have been so dramatically altered and reduced as to make learning them even more difficult IMO. What happened to all the text and content?

How can I get yesterday's version?

**Comment by OmarSquircleArt** [comment]
Only two examples were altered, extra examples were added, significantly more explanation have been introduced. Not sure what you are talking about.

You can find the previous version here:

https://github.com/JacquesLucke/animation_nodes_manual/blob/d70b32170458c34290041704575ab5bd6bef60bc/docs/user_guide/subprograms/loop.rst

**Comment by RodeyOrg** [comment]
Thanks OmarSquircleArt, it was for example 6, which originally I thought seemed to have been abbreviated, but glad to have the original also now. Thanks for the efforts anyway.

**Comment by RodeyOrg** [comment]
> Only two examples were altered, extra examples were added, significantly more explanation have been introduced. Not sure what you are talking about.
> 
> You can find the previous version here:
> 
> https://github.com/JacquesLucke/animation_nodes_manual/blob/d70b32170458c34290041704575ab5bd6bef60bc/docs/user_guide/subprograms/loop.rst

Something is not right here IMO

Please, for example, look at example 6 the on your updated Subprograms > Loops page

https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/loop.html

And then look at it on the original you sent.

https://github.com/JacquesLucke/animation_nodes_manual/blob/d70b32170458c34290041704575ab5bd6bef60bc/docs/user_guide/subprograms/loop.rst

There is on the updated version significant sections of text removed

**Comment by OmarSquircleArt** [comment]
And the updated example (Example 8 in the new page) is as follows:

> In this illustrative example, we have two node trees that supposedly does the same thing, that is, hide the objects in a blender group and then show them. The only difference is, in the node tree on the right, we used the iterator as an output and used that output as the iterator of the second loop, while on the left node tree, we used the object list directly for both loops.
> 
> loop_example8.png
>
> Those two node trees are actually not the same, the left node tree shouldn’t be used for two reasons:
> 
> - There is no defined order for the loops to execute. Should Animation Nodes execute the upper or the lower loop first? There is no way to know, so Animation Nodes executes them in arbitrary order. This causes unexpected results because if the show loop was executed first, the object will end up hidden because the hide loop will execute second.
> - Even though the object list is not edited, Animation Nodes copy it thinking you wanted two different copies.
>
> The right node tree fixes both problems by:
> 
> - Defining an order for the loops to execute by making the second depend on the output of the first, thus instructing Animation Nodes to execute the dependencies first.
> - The object list is not copied because it is used sequentially, that is, no branching occur.
>
> In conclusion, the right setup should be used at all times.

Moreover, the the Iterator Sockets section include some info on this as well:

> If iterators are presents, an option Use {Iterator} As Output for each of them will be displayed, if enabled for an iterator, the iterator will be available as an output when the loop is invoked. The output will be the same list you input. This is useful to avoid unnecessary data copying by using the output instead of creating another branch from the source iterator which would enforce data copying. Moreover, this also ensures that the loop executes first as a consequence of the series connection. See examples below.

To me, this seems much better in structure, easier to understand, more accurate, and more comprehensive. If you want, I can poke Jacques to have a say in this.

**Comment by RodeyOrg** [comment]
OK got it, it's the example number changes that initially threw me. Not sure if nudging Jaques is required on this point, your call. Thnx.

**Comment by RodeyOrg** [comment]
I haven't been through all examples forensically and maybe I missed it but this example is missing in the new version—if so can I ask why?

> At the first iteration, the iterator was 16 and it gets assigned to the parameter because of the equal to zero condition, at the second iteration, the iterator was 36 which is larger than the current parameter value which is 16 (assigned from the last iteration), so I reassign the parameter to be 36, at the third iteration, the iterator is -25 which is not larger than the current value of the parameter 36 so we don't assign it. Since we enabled the output option for the parameter, it is available as an output for the subprogram carrying the last assigned value which was 36 which is the largest value.

It could be helpful in explaining difficult the concepts of the loops/node setups etc.

**Comment by OmarSquircleArt** [comment]
This is *Example 9* in the new version. It is true that we omitted the iteration-by-iteration demonstration, but that was intentional, notice that we say:

> Since we reassign whenever the integer is larger than the integer stored in the parameter, we end up with the largest integer, why? Take your time to think about it.

This encourages the reader to perform the iteration-by-iteration process oneself, and thus have a better understanding of it. Open Animation Nodes and try those examples yourself.

---
As for the typos, if you know how to use git/github, you can create a pull request with the fixes yourself. If you are not familiar with the process, you can create an issue pointing out those typos and we will fix it. Thanks in advance !

**Comment by OmarSquircleArt** [comment]
[Example 9](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/loop.html#example-9) explains reassigment operator in a simple manner, [Example 10](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/loop.html#example-10) challenges the user in an iteration-by-iteration demonstration. So we did exactly as you said, we explained the reassignment operator it in details in an example (9) and challenged a demystification for it in (10).

As for the missing steps, we already covered that in the [Parameters Sockets](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/loop.html#parameter-sockets) section. If the reader read that, the reader would be capable of understanding the little steps. Are we expected to explain it in every example? That would be tedious.

**Comment by RodeyOrg** [comment]
Oops maybe a small misunderstanding but I meant an explcit example from the old version below.

[Example 7](https://github.com/JacquesLucke/animation_nodes_manual/blob/d70b32170458c34290041704575ab5bd6bef60bc/docs/user_guide/subprograms/loop.rst#example-7https://github.com/JacquesLucke/animation_nodes_manual/blob/d70b32170458c34290041704575ab5bd6bef60bc/docs/user_guide/subprograms/loop.rst#example-7)
(legacy version)

Anyhow I'm happy to leave it here—the manual changes have been made so it's probably more productive that I enquire for more explcit clarifications or use legacy doc you kindly provided.

Thanks again @OmarSquircleArt

**Comment by OmarSquircleArt** [comment]
We are constantly trying to improve the documentation and your feedback is most welcome. We will rewrite some portions of the documentation on Loops based on your feedback. If you think any other part of the documentation needs improvements, please lets us know and we will improve it in matter of days. Alright?

**Comment by RodeyOrg** [comment]
> 
> 
> We are constantly trying to improve the documentation and your feedback is most welcome. We will rewrite some portions of the documentation on Loops based on your feedback. If you think any other part of the documentation needs improvements, please lets us know and we will improve it in matter of days. Alright?

Perfect.
