### ISSUE TITLE
Subprogram: Find First Occurence (Example 11)

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes_manual#50]
This works all fine for me in Blender which is great, so only just needed clarification on a couple small points so I am clear on the inner workings of this setup etc. 

> We start by adding a dummy integer parameter whose initial/default value is equal to negative one, 

I couldn't see anywhere in the example exactly where this negative 1 (-1 ?) dummy number had been added—I could only see the Math Node where _we **add** +1 to the index_  

> At the time of the break happened, the current iteration index is the index we are looking for, but the breaking happen before the reassignment—or any other operation in the node—, so the current index never gets written to the parameter, 

I wasn't clear why the break happened _before_ the reassignment? As the _reassigned index socket_ is at the top of the loop input node I presumed, (it seems incorrectly), that that might be the order the processing followed also. 

**Is my understanding on the _order/sequence_ of the loop and nodes processing correct as below?** 

1. Intger List is fed to Invoke Subprogram Node
2. _Reassigned Index is outputted (so viewer receives it)?_  
3. Loop Input Node (first step in the Subprogram) feeds it's inputs to the Compare Node
4. Compare Node output is fed to Loop break test continuing only if A!=B

It's step 2 that I am most unclear on.

**Comment by OmarSquircleArt** [comment]
The dummy parameter is the parameter called *index*, we add it just as any other parameter, but, we set its default value to -1, use it as an output and hide it as an input. All of this can be done from the [advanced node settings](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/loop.html#parameter-sockets) of the parameter.

The order of operations in the loop is as follows:

1. Parameters and iterators are fed to the loop.
2. All nodes in the loop are executed.
3. Break—if available—is executed.
4. Generators—if available—is executed.
5. Reassignment—if available—is executed.

So the breaking happens **before** generators or reassignment operators are executed. 

Thanks for bringing this to our attentions, we shall add it in the documentation.

**Comment by RodeyOrg** [comment]
Thank you, in particular for the processing order. 

Re the dummy parameter, the funny thing is, as mentioned I didn't know how to do this, but yet my program *apparently runs flawlessly without it. 

I probably need to check the veracity with more outcome. But so far I think I get the results you do without this dummy value.

I can try to reread what you wrote to understand better what you are doing there with the dummy value (and subsequently why I need it in the Subprogram routine).

**Comment by OmarSquircleArt** [comment]
Added more information about the execution mechanism of loops in 1fadd09.
