### ISSUE TITLE
Create Spline List

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes_manual#55]
Hi

[Create Spline List Example](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/spline/create_spline_list.html#examples-of-usage)

I've followed this example near as much as the detail provided (see attached) but cannot yet replicate the scene you have in yours.

Can you detail any further what you did to get it exactly please?

![screen shot 2018-11-07 at 23 12 59](https://user-images.githubusercontent.com/44178760/48167160-c2979380-e2e2-11e8-86d0-0fa584905eba.png)

**Comment by OmarSquircleArt** [comment]
We are just duplicating the spline in edit mode. See the *Connect Splines* node for more info. We should probably remove this example from such a simple node.

**Comment by OmarSquircleArt** [comment]
Fixed in 7cf97eed0d512b348b0c9b032a5080dce60da41e.

**Comment by RodeyOrg** [comment]
OK got it.
