### ISSUE TITLE
Number Wiggle: Amplitude vs Persistence

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes_manual#59]
Hi

[Number Wiggle](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/number/number_wiggle.html#description)

What is the difference between Amplitude and Persistence?

They seem to do much the same thing and the explanations were good though quite complex so I mostly used the very helpful images and basing query on that.

**Comment by OmarSquircleArt** [comment]
*Persistence* is the magnitude of the smaller waves/details while the *Amplitude* is the magnitude of the first octave, that is, the biggest wave. Does that make sense?

**Comment by RodeyOrg** [comment]
> 
> 
> _Persistence_ is the magnitude of the smaller waves/details while the _Amplitude_ is the magnitude of the first octave, that is, the biggest wave. Does that make sense?

Thanks, though sorry not yet _or not entirely clear at least._ 

May I reword it at a high level to confirm if I am even on the right track. 

_Persistence_ is like a threshold - which determines the _minimum_ point at which (smaller) waves appear?

_Amplitude_ is the maximum size the wave can reach?

Amplitude, I think is clearer to me.

**Comment by OmarSquircleArt** [comment]
No, not exactly. The wiggle node evaluates what is known as a perlin noise. A perlin noise is a function composed of random value smoothly connected to each other forming something like a random wave. The amplitude of the noise is the maximum random value possible (And negative the amplitude is the minimum random value possible). Now, to make the noise more interesting, the wiggle node add multiple perlin noises over each other, each one is called an *Octave*. An octave usually have a higher frequency than the previous octaves. Moreover, each octave—being a perlin noise itself—have an amplitude that is proportional to the *Persistence* value. Thus we can say that the *persistence* is the constant of proportionality of the amplitude of the octaves. In conclusion, you can think of octaves as level of details and the persistence as the effect of each octave to the final function.

**Comment by RodeyOrg** [comment]
Thank you. I can review this again, and try to make sense of it.
