### ISSUE TITLE
Cannot choose which Python to use when compiling AN

### ISSUE THREAD

**Issue by nantille** [JacquesLucke/animation_nodes_manual#60]
Hello,

I have a custom build of Blender and I'd like to compile AN against a Python version (here 3.6.2 but in other cases 3.6.6 and even 3.7.1) that I want to specify when running setup.py

Could you add the option in setup.py (or in the install config) to specify the python executable and libs? Or is there an environment variable to set before running setup.py? 

I tried compiling on MacOS with Python 3.7.1 and it worked but I want to have a way to specify another version that is not the default Python when calling python3 in the terminal.

Thanks,
Nicolas

**Comment by OmarSquircleArt** [comment]
You can use the `--noversioncheck` flag when building. This will allow you to build with any python version you want.

**Comment by OmarEmaraDev** [comment]
If you are still having issues, feel free to reopen.
