### ISSUE TITLE
Vertices Numbering

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes_manual#62]
Hi, a small thing,

https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/falloff/fade_falloff.html

I've searched but haven't yet found how to number the steps (0-9 as in this example), could someone please show me where the option is for this, or was it manually done?

Thanks

**Comment by OmarSquircleArt** [comment]
Animation Nodes provide an option to visualize vertex, edge, and polygon indices. For v2.7x, this option is available in the *Display* panel in the *N* menu in the *3D Viewport*. For v2.8, this option is available in the *Overlay* thingy.
![Option Location](https://user-images.githubusercontent.com/25300994/54867050-b0475f00-4d84-11e9-896b-3d9b9e24407b.png)

**Comment by RodeyOrg** [comment]
OK great, being on 2.79 I have opened the file, mouse hovers over 3D Viewport, clicked N, gone to display panel and do not see any options _relating to vvisualizing vertex edge_ etc. I even tried in edit mode.

I do though see World Background, Only render, Outline Selected, All Object Origins and Relationship lines, Grid floor etc. 

It could be staring me in the face but as of yet no joy.

**Comment by OmarSquircleArt** [comment]
It only works in Object mode, it should be in the Display panel under the label "Show Mesh Indices:". I am not on 2.7x so I can't really screenshot or check it.

**Comment by RodeyOrg** [comment]
> 
> 
> It only works in Object mode, it should be in the Display panel under the label "Show Mesh Indices:". I am not on 2.7x so I can't really screenshot or check it.

OK thanks I can try this, 

Is AN now fully functional in 2.8?

**Comment by OmarSquircleArt** [comment]
@RodeyOrg I believe everything works except rendering. Though the latest blender build may not work for the moment.
