### ISSUE TITLE
Animation Nodes 2.0 for Python 3.7.0

### ISSUE THREAD

**Issue by jkauso** [JacquesLucke/animation_nodes_manual#64]
Hi,

Due that the RTX GPU does not work with all blender versions, I am using a Blender with Python 3.7.0.
For that reason I want to make a custom build for Animation nodes 2.0 that uses Python 3.7.0.

I tried to follow the manual, but I'm not a coder type and I cannot get it done myself.

Is there maybe already a Animation nodes 2.0 versions for Python 3.7.0 somewhere that I can just download?

**Comment by OmarSquircleArt** [comment]
I don't think there is a 3.7 build for 2.0. It is very unlikely that there will be one. Your only option is to compile it on your own. Or find someone who is willing to.
