### ISSUE TITLE
Break when upgraded to 2.1.2

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes_manual#66]
In tryng to get the _Polygon Offset node_ I upgraded to AN 2.1.2 from 2.0.4 and seem to have broken all previous projects I had been using to learn AN. For example the example you provided in _Prepare Polygons Transformation_—was this to be expected and I have to find new ways to do things (i.e. using different nodes than as provided in manual that I had been referring to)?

**Comment by OmarSquircleArt** [comment]
Yes, we will not be updating the manual unless we are very close to the release of the next build, which will probably be for 2.8. Animation Nodes usually breaks backward compatibility, so some of your older projects may no longer work.

**Comment by RodeyOrg** [comment]
OK got it, thnx.

Thanks. I was thinking of submitting a reworded description of this node
based on our discussion here, ( for eg not realising that the matrix
transformation ), but it seems this node will be deprecated in later
versions.
