### ISSUE TITLE
Object Mesh Data Example

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes_manual#69]
Hello, 

https://animation-nodes-manual.readthedocs.io/en/latest/release_notes/v2_0/mesh.html#object-mesh-data

For some reason I did not get my example to work as yours does?

Thanks

![Screen Shot 2019-08-01 at 23 34 51](https://user-images.githubusercontent.com/44178760/62331862-3737e100-b4b5-11e9-999e-81f44fd82276.png)

![Screen Shot 2019-08-01 at 23 34 43](https://user-images.githubusercontent.com/44178760/62331864-3737e100-b4b5-11e9-88f5-8dae5071a9d6.png)

**Comment by OmarSquircleArt** [comment]
Just scale down your objects.

**Comment by RodeyOrg** [comment]
> Just scale down your objects.

Not entirely clear on this above, as I had already scaled the cylinder object (down) and it had no affect on the effect, essentially I had made the cylinder small but as soon as I used the _scale_ in the vector math node I got the issue as outlined.

_Anyway I think I have it, unlike the example I had to have copy full pobject enabled. I still don't know why our examples differ though._

**Comment by OmarSquircleArt** [comment]
@RodeyOrg Enable the Scale option in the *Object Transform Output* node then scale the cylinders down from there. The *Copy Full Object* option copy the scale of the object, but it is not updatable.

**Comment by RodeyOrg** [comment]
Thanks
