### ISSUE TITLE
Animate evolution?

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes_manual#70]
https://animation-nodes-manual.readthedocs.io/en/latest/_images/separate_polygons_node_example.gif

I've tried various setups to try and animate the evolution input, to no avail as of yet. Can someone kindly show me a setup that works?

**Comment by OmarSquircleArt** [comment]
What did you try? Have you tried connect the frame output of the *Frame Info* node to the evolution input?

**Comment by RodeyOrg** [comment]
Yes, I tried this and all sorts of exotic vartions. No joy as of yet, odd.

![Screen Shot 2019-08-06 at 15 48 09](https://user-images.githubusercontent.com/44178760/62550143-a91b7c00-b861-11e9-96fa-6fe2459293c3.png)

**Comment by RodeyOrg** [comment]
Update: Not sure if this qualifies as a bug, but here's what I did to fix. 

I copy pasted the nodes into a new blender file, I then created new instances of the icosphere for the nodes and voila it animates as originally expected. For some reson the exact same setup doesn't work in the previous blender file with exact same settings.
