### ISSUE TITLE
Materials on separated-polygons

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes_manual#73]

**Comment by RodeyOrg** [comment]
Hello, I am experiementing with this here again

https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/mesh/separate_polygons.html

But when I try to add a material to each polygon I get this:

![Screen Shot 2019-12-14 at 20 05 00](https://user-images.githubusercontent.com/44178760/70854003-c31f3800-1ead-11ea-9410-deb7b4fdf1ea.png)

AN 2.79b
Mac

**Comment by OmarEmaraDev** [comment]
The target object is just intersecting with the original object. Right?

**Comment by RodeyOrg** [comment]
Aha, thanks I think I may understand what you mean - am I guessing right that I should then hide original and that target will carry the original's material?

**Comment by OmarEmaraDev** [comment]
Yes. But the target won't get the material automatically. You can either add it manually or use the new Material nodes.

**Comment by RodeyOrg** [comment]
Thanks
