### ISSUE TITLE
Separate Polygons/Combine Mesh does not work as documented.

### ISSUE THREAD

**Issue by bholzer** [JacquesLucke/animation_nodes_manual#74]
I tried to use the method described in the docs here: https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/mesh/separate_polygons.html

Without the "Edge Indices" input being filled in "Combine Mesh", the Combine Mesh node says "A polygon requires an edge that does not exist"

How can I separate mesh properly?

**Comment by OmarEmaraDev** [comment]
Starting from version 2.1, the *Combine Mesh* requires edges to be explicitly given. You may compute edges using the *Edges Of Polygons* node.

**Comment by bholzer** [comment]
I tried this and got results that were quite unlike what I expected. Will post a picture shortly.

**Comment by bholzer** [comment]
That's what I suspected, but adding an "Edges of Polygon" node doesn't give me anything like the expected result. 

![Icosphere using the documented process with the addition of an Edges of Polygon node](https://user-images.githubusercontent.com/1375965/72539616-2dc4ea00-3845-11ea-8206-29fdf44efac9.jpg)

**Comment by bholzer** [comment]
Well, I feel silly. Reducing the vector wiggle amplitude has this working as expected. Thanks for the help, and sorry for the trouble!
