### ISSUE TITLE
No documentation for "Mesh Info"

### ISSUE THREAD

**Issue by johnnybigoode** [JacquesLucke/animation_nodes_manual#76]
While minor, at least one other person found issues with this, specially because tutorials around the web are not properly updated:

https://blender.stackexchange.com/questions/166356/the-grid-mesh-generator-has-changed-its-outputs-how-do-i-turn-its-mesh-output-t/166467#166467

**Comment by OmarEmaraDev** [comment]
We haven't started documenting v2.1 yet.

**Comment by johnnybigoode** [comment]
Oh. @OmarEmaraDev I was going to update the manual and do the pull request thing. 

Just noticed that the 2.1 version is under tests. Sorry about that.

**Comment by OmarEmaraDev** [comment]
Hey @johnnybigoode, we decided to start documenting v2.1. Feel free to submit a pull request to the master branch if you want.
