### ISSUE TITLE
How to create Structure Synth in new versions animation node?

### ISSUE THREAD

**Issue by jason800811** [JacquesLucke/animation_nodes_manual#77]
Hi, I'm a new learner of an animation node. 
I try to follow this tutorial to create a structure: 
https://www.youtube.com/watch?v=tLCUc4i2yuQ

basically, I want to generate the shape base on the structure and the object I create(like this B in the tutorial).

<img width="1413" alt="螢幕快照 2020-02-25 下午10 01 34" src="https://user-images.githubusercontent.com/61463866/75254151-e013a800-581a-11ea-8a03-2bc4ed79e073.png">

But I found that the name and the function are different in the new version of animation node, I could not found the right node.

<img width="1467" alt="螢幕快照 2020-02-25 下午10 08 28" src="https://user-images.githubusercontent.com/61463866/75255313-afcd0900-581c-11ea-8bf0-4aa4075a93e8.png">

Do some know how to make it?

Thanks!!

**Comment by OmarEmaraDev** [comment]
Which node can't you find exactly?

**Comment by jason800811** [comment]
Replicate Mesh Data
<img width="936" alt="螢幕快照 2020-02-25 下午11 16 48" src="https://user-images.githubusercontent.com/61463866/75260696-f6266600-5824-11ea-8c4e-97ef94a56d96.png">

**Comment by OmarEmaraDev** [comment]
The Replicate Mesh node was removed and replaced by the Transform Mesh node. They work very similarly, so it should be a drop in replacement.

**Comment by jason800811** [comment]
Hmm.. but the transformation is an orange dot, I cant not connect it to the vertex location of my object mesh data below. How can I solve this?
<img width="855" alt="螢幕快照 2020-02-25 下午11 45 25" src="https://user-images.githubusercontent.com/61463866/75263743-5c14ec80-5829-11ea-86fe-a42b2ae8b627.png">

**Comment by OmarEmaraDev** [comment]
The node have two modes, Matrix and Vector. You need to use the Vector mode.

**Comment by jason800811** [comment]
Ok. Why there is a problem when I try to connect polygon indices from mesh info and combine mesh?
<img width="808" alt="螢幕快照 2020-02-25 下午11 56 04" src="https://user-images.githubusercontent.com/61463866/75264748-d5f9a580-582a-11ea-9eb5-690655fbe278.png">

**Comment by OmarEmaraDev** [comment]
You need to connect the edges as well. But I fail to see why you need those nodes. Just put the mesh directly.

**Comment by jason800811** [comment]
I did it. Thank you so much!!!!

<img width="1235" alt="螢幕快照 2020-02-26 上午12 06 15" src="https://user-images.githubusercontent.com/61463866/75265666-30dfcc80-582c-11ea-96f0-1265449749cb.png">

**Comment by OmarEmaraDev** [comment]
Good to hear. I suggest you ask in https://blender.stackexchange.com/ in the future, as this is more of a documentation repository.
