### ISSUE TITLE
LSystem 

### ISSUE THREAD

**Issue by purelazy** [JacquesLucke/animation_nodes_manual#78]
I can't find any documentation for the L-System node. Is there any?

Cheers,
Andre

**Comment by OmarEmaraDev** [comment]
L-System was added in v2.1, which is yet to be released. The documentation will be added as soon as we release v2.1. Jacques made couple of videos about L-Systems though, so you may watch those meanwhile.

**Comment by purelazy** [comment]
I was watching a video by Chris Prenninger.  I will check out Jacques' videos. too.
