### ISSUE TITLE
The New Documentation

### ISSUE THREAD

**Issue by OmarEmaraDev** [JacquesLucke/animation_nodes_manual#80]
Preparing for the next release of Animation Nodes, we decided to rework the documentation. In this post, I shall outline what we are trying to do, what we already did, and what we need to do in the coming weeks.

# Migration

We migrated the documentation from Sphinx/ReadTheDocs to Hugo. There are many reasons why we think Hugo is better than Sphinx/ReadTheDocs, some of those reasons are as follows.

- Performance. Hugo can build the whole documentation in less than 2 seconds, from scratch, yes, that's 100x faster than Sphinx.
- No dependencies. Hugo is a binary with no dependencies whatsoever. You don't need to install a python runtime, you don't need extra modules, you don't need anything special, just install and build. This should reduce the barrier for contributions.
- Live Reloading. Hugo builds and reloads pages on the fly, so it is more friendly to use.
- CommonMark. We use the standard commonmark markdown markup language. We no longer have to deal with the complexity of RST.
- Extensibility. We can extend the documentation using Go's templating functionality, which is rather easy to use and is well documented.

The documentation was also migrated to Animation Nodes's web server, and it will be available at https://docs.animation-nodes.com/.

# Content

## Organization

The structure of the documentation changed into *leaf pages* with some category *branch pages*. Leaf pages allow each page to have its resources self contained, which will make it easier to track, add, and refactor. Branch pages usually represents categories and should generally list their children. The following figure demonstrates the new structure.

```
 |-documentation
 | |-subprograms
 | | |-_index.md
 | | |-invoke
 | | | |-index.md
 | | | |-one_time_cache.png
 | | | |-once_per_frame_cache.mp4
 | | | |-once_per_input_cache.mp4
 | | | |-change_subprogram.png
 | | |-expression
 | | | |-index.md
 | | | |-expression_node.png
 | | | |-expression_node_example_1.png
 | | |-group
 | | | |-index.md
 | | | |-network_error.png
 | | | |-group_example_2.png
 | | | |-group_example_1.png
 | | | |-invoke_example_1.png
 ...
```

We have three leaf pages (`index.md`) and one branch page (`_index.md`). Each page have its own resources next to it.

## Media

We converted all gifs into H264 videos in mp4 containers. We will no longer allow gifs in the documentation. In most cases gifs are of inferior quality and of much higher size. The videos are, of course, inlined and autoplayed, so the user shouldn't notice any difference, aside from the faster load times. Videos are added using the `video` shortcode as follows.

```
{{< video an_example_video.mp4 >}}
```

## Front Matter

Pages needs to have a *Front Matter* that describe its contents. We can write the front matter in YAML, TOML, or JSON. Our choice for the front matter format is YAML, but most pages only have one or two simple YAML statements as shown in the following front matter, so this shouldn't be a problem to those unfamiliar with YAML.

```
title : Example Page Title
chapter : true
```

# Issues

## Deployment

Currently, we deploy the documentation using the `lftp` FTP client. The problem is, it takes about 30 minutes to deploy the website, as it uploads everything, not just the changes. It is unclear to me if this is something we can solve somehow, but we definitely need to find a better way to handle deployment.

## Automatic Migration

The content was migrated mostly automatically, so we expect there to be bad content which we will have to iron out manually.

## Page Order

Currently, pages are ordered by their weight, a value that is defined in the front matter. This is bad because if we want to add a page in the middle, all pages after it will be have to be updated.

# Practical Documentation

## The Problem

The main problem we have with the documentation is that it is not practical, it nothing more than a mere reference in most cases. Even the examples provides are superfluous and are more of a demonstration than an actual practical example. Asking developers and documentation writers to provide more practical examples is ... not practical. Can you think of a practical example for a node that returns the maximum number in a number list? You see what I mean?

## The Proposed Solution

Multiple users pointed to me that my answers on StackExchange were far more useful than the official documentation. That's why I mostly concerned myself with helping users on StackExchange than improve the documentation, but that was before I left StackExchange.

That's why I am proposing a new way of writing practical documentation for Animation Nodes. First, the *Example Of Usage* section of nodes will be removed. Instead, a new section that only contains references to *"Example Pages"* will be added. An example page is a page that follows a tutorial like structure, where the author describe how to reproduce a certain setup in Animation Nodes. An example is not related to a particular node, it only occasionally use the nodes that references it.

But how do we populate those examples? The example page will be populated in a Q&A manner. Users can ask questions here on this repository, on StackExchange, or in any other network. Once the question is answered, the answer can be promoted into an Example Page or it can be used to improve a certain documentation page. #56 is one such question that can receive an answer than can improve the documentation.

The Q&A style documentation writing ease the burden from the documentation writer and makes a stronger connection with the end-user.

**Comment by JacquesLucke** [comment]
I do like the idea of example pages. I think that can work well. However, I'm not sure if we should allow users to ask AN usage related questions in issues in this repo. The issue tracker should not become a support forum.

Users usually have way to specific problems. While it is not bad to have specific examples, there are too many specific problems than I'd like to have open issues. Either we need some strict moderation, or we only allow issues that already provide a solution. 
StackExchange seems to be a much better place for users to ask questions. We can merge good answers into the docs.

----

I wonder, how much value provide the screenshots of individual nodes? Maybe we could just omit them as well?
I do think that a very short video with a small node setup is useful for some nodes; Just so that one can get a better idea of how a node behaves when the description is too abstract. That is not necessary for all nodes of course.

**Comment by OmarEmaraDev** [comment]
> I wonder, how much value provide the screenshots of individual nodes? Maybe we could just omit them as well?

That's a good point. Often the screenshot only shows one mode of operation of the node as well, so it is not fully informative in most cases either.

> I do think that a very short video with a small node setup is useful for some nodes.

I agree. Notice that for some nodes, we have a "Demonstration" section, it usually includes a simple setup that demonstrates the operation of the node. So we can continue to improve the documentation by providing more demonstrations.

> The issue tracker should not become a support forum.

Sounds reasonable. Though I don't think StackExchange is the solution to our problem. We can look into other means of populating the examples.

**Comment by Gerstmann-Bradley** [comment]
Referred from #1579.
I agree to convert GIF into MP4. as long as we gonna have a "video"-like demonstration, it will be fine.
Despite practicality issue mentioned in later paragraph. A video demonstration is more vivid than stone-cold language used to describe input/output in the manual.

When talking about practicality, there are several issues:
1.	user's goals are different and maybe too specific.
a)	“Your practical example maybe useless to me when I don’t need it”
b)	Users may come from different backgrounds, coder Vs. non-coder…
c)	it’s user’s responsibility to learn and think. Different animation may be based on the same technique; No way to prevent users from asking the same technique for a different animation.
2.	Actual node tree for many practical examples maybe rather large and complicate/advanced.
a)	**"Practical" Examples may rather raise more questions than ever**.

Thus, my opinion is:
1.	As simple demonstrations as in the past are good enough.
2.	If it already has a “demonstration” section, a further dig into “practical example” may not be as helpful to users as expected.
3.	Instead, it’s ok just to provide general resources to users.
a)	Most commonly people learn something from youtu video.
b)	people can ask specific question on BSE (Or any other suggestible places?)

**Comment by OmarEmaraDev** [comment]
@Gerstmann-Bradley Practical examples is not exactly my intention, that' why I said in a "tutorial-like structure". So it is essentially giving an example in a certain practical context, which I think is what you want.

**Comment by Gerstmann-Bradley** [comment]
> @Gerstmann-Bradley Practical examples is not exactly my intention, that' why I said in a "tutorial-like structure". So it is essentially giving an example in a certain practical context, which I think is what you want.

A tutorial-like structure maybe nice despite amount of work that needs to be done.

What I initially asked was basically the examples shown in the old manual. I agree with the mentioned post that those are important and urgent to be done. (whether make new one or just upload the old ones for the timing.)
(Seems you call it "demonstration" now. I am fine with the name regardless, but I hope it doesn't cause confusion during discussion)
1. Those were mostly short and easily reproducible so that people can play around nodes and parameters to learn by their own.
2. It can be a starting point to learn other nodes by reading manual of one node.
Reading  the manual of a single node still doesn't lead to a functional node tree. It can be hard to know the relationship  between nodes for a beginner. Take "transform vector" node as an example, I know it needs a vector input, but which node outputs a vector?
I don't expect people to finish reading a whole dictionary in order to speak English, Neither nor I expect people to finish reading a whole manual to know how nodes should be connected to each other.

I will finish here. Thanks for your effort, I appreciate that.

**Comment by nexus12** [comment]
Is there a link to the old documentation? As I wanted to look at the examples for the quarternion nodes. Thankyou

**Comment by OmarEmaraDev** [comment]
@nexus12 See the v2.0 branch in this repository: https://github.com/JacquesLucke/animation_nodes_manual/tree/v2.0/docs/user_guide/nodes/rotation

**Comment by nexus12** [comment]
Thankyou very much!
