### ISSUE TITLE
AN 2.2 linux py37 fails

### ISSUE THREAD

**Issue by linuxuser63** [JacquesLucke/animation_nodes_manual#84]
I am using Blender 2.92 and downloaded the module for blender 2.92 with python 3.7.  Tried to use and got the following error:
Traceback (most recent call last):
  File "/opt/blender-2.92.0-linux64/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/leon/.config/blender/2.92/scripts/addons/animation_nodes/__init__.py", line 158, in <module>
    raise Exception(message)
Exception: 

This build does not work at the moment.
  1. Check if the build you downloaded has been compiled for the OS
     you are using. If not, download another one.
  2. If you are on windows you can try to install a library called
     'vc_redist.x64'. Should be easy to find using your search engine
     of choice.
  3. Try to use an official Blender release downloaded from blender.org.
  4. It is possible that you have a build for the correct platform
     but it still does not work. We experienced this mainly on linux.
     Try to find another build for your platform.
     If it still does not work, you have to compile AN yourself.
  5. Make a bug report on Github and give as much information
     as you can. Specifically the full error message, your OS, version, ...
Am using Blender:
Blender:

version: 2.92.0, branch: master, commit date: 2021-02-24 16:25, hash: 02948a2cab44, type: Release
build date: 2021-02-25, 09:31:37
platform: Linux
binary path: '/opt/blender-2.92.0-linux64/blender'

Python:
version: 3.7.7 (default, Jul  9 2020, 12:52:49)  [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
file system encoding: utf-8:surrogateescape
paths:
	'/opt/blender-2.92.0-linux64/2.92/scripts/startup'
	'/opt/blender-2.92.0-linux64/2.92/scripts/modules'
	'/opt/blender-2.92.0-linux64/2.92/python/lib/python37.zip'
	'/opt/blender-2.92.0-linux64/2.92/python/lib/python3.7'
	'/opt/blender-2.92.0-linux64/2.92/python/lib/python3.7/lib-dynload'
	'/opt/blender-2.92.0-linux64/2.92/python/lib/python3.7/site-packages'
	'/opt/blender-2.92.0-linux64/2.92/scripts/freestyle/modules'
	'/opt/blender-2.92.0-linux64/2.92/scripts/addons/modules'
	'/home/leon/.config/blender/2.92/scripts/addons/modules'
	'/opt/blender-2.92.0-linux64/2.92/scripts/addons'
	'/home/leon/.config/blender/2.92/scripts/addons'

Python (External Binary):

binary path: '/opt/blender-2.92.0-linux64/2.92/python/bin/python3.7m'

I tried building my own but that failed, too.

Submitted per instructions on the error message
Thank you

**Comment by OmarEmaraDev** [comment]
Try installing the shared python library. See https://github.com/JacquesLucke/animation_nodes/issues/1240.

**Comment by OmarEmaraDev** [comment]
Can you list the shared object dependencies of the AN test compile library? In the installed `animation_nodes` directory, execute:

```
ldd test_compile.cpython-37-x86_64-linux-gnu.so
```

**Comment by OmarEmaraDev** [comment]
For 3.7, `libpython3.7m.so.1.0 => not found` tells us that the shared python library doesn't exist and needs to be installed, I don't know how to do that in Mageia 8.

2.93 uses Python 3.9, which you don't have. 2.92 is not supported for the latest AN, but you can try the `Latest (Python 3.8)
` from the download page, which is a slightly older version before we started on the 2.93 efforts.

If non of those options works, I am not sure what your best course of action is. Probably build master for 2.93 with python 3.9.
